version: '3.8'

services:
  chat:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=app.py  
      - FLASK_DEBUG=1
      - FLASK_ENV=development